### ISSUE TITLE
Add support for Zola 

### ISSUE THREAD

**Issue by kunjee17** [nxrs/cargo#10]
As this is supporting or will be supporting almost everything related to rust. It would be great to have [Zola ](https://www.getzola.org/) support as well.

**Comment by IgnisDa** [comment]
@kunjee17 What exactly would you expect a zola executor to support?

**Comment by kunjee17** [comment]
@IgnisDa zola commands can be executed via Nx

**Comment by IgnisDa** [comment]
@kunjee17 I don't see why this should be a part of `@nxrs/cargo`. There are many rust based frameworks out there, it would be out of scope for `@nxrs/cargo` to support out of them. Perhaps a better solution would be to create a new plugin.

**Comment by kunjee17** [comment]
@IgnisDa got it. Closing the issue for now.
