### ISSUE TITLE
cargo.exe popup window on save (windows)

### ISSUE THREAD

**Issue by 20Koen02** [nxrs/cargo#12]
When I run the serve target on all projects (I'm not using any serve target on the rust project, so it's not running) a cmd window pops up. When i look in task manager I see that the cargo.exe process is running in that command window. Everytime I save a file and the automatic reloader triggers, the cmd window pops up for a couple seconds and then closes. When I remove the `"plugins": ["@nxrs/cargo"]` line in de nx.json file the issue issue no longer occurs. This only happens on windows 10, this does not happen on my linux machine

**Comment by dannymcgee** [comment]
Thanks for the report @20Koen02 — would you be able to send me a link to your project so I can try to get a better idea of what's happening?
