### ISSUE TITLE
target option for build seems to be ignored / not implemented

### ISSUE THREAD

**Issue by ndrsg** [nxrs/cargo#14]
```json
    "build": {
      "executor": "@nxrs/cargo:build",
      "options": {
        "release": false
      },
      "configurations": {
        "production": {
          "release": true
        },
        "windows": {
          "target": "86_64-pc-windows-gnu", <--- this is ignored
        }
      }
    },
```

Cannot specify target, cargo keeps building with its default, so no cross-compilation is possible

**Comment by dannymcgee** [comment]
Hey @ndrsg, thanks for the report. It looks like I completely forgot about that in my arguments parser. It should be a pretty straightforward fix.

**Comment by dannymcgee** [comment]
@ndrsg Please update to v0.3.3 when you get the chance and let me know if the issue is fixed

**Comment by ndrsg** [comment]
@dannymcgee : thanks for your fast fix. sadly I will not be able to test before upcoming monday, but it'll be the first i'm going to do next week.
Thanks for this really cool and useful nx extension! (:

**Comment by ndrsg** [comment]
Your fix works :) Thanks again!
