### ISSUE TITLE
TypeError: builder.addDependency is not a function

### ISSUE THREAD

**Issue by mmmoli** [nxrs/cargo#2]
Hi there,

I'm trying this out. Want to flag:`build` and `lint` commands fail with
```
builder.addDependency(devkit_1.DependencyType.static, pkg.name, depName);

TypeError: builder.addDependency is not a function
```

Using 12.6.2 of nx.

**Comment by dannymcgee** [comment]
@mmmoli Thanks for the report! Looks like there was an upstream API change that I hadn't caught. Should be fixed in 0.3.1 — let me know if you run into any other issues!
