### ISSUE TITLE
Plugin defines cargo dependencies to be implicit dependencies

### ISSUE THREAD

**Issue by IgnisDa** [nxrs/cargo#22]
Here is a project graph:
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/60938164/182009570-eac9454b-2698-40e9-adb4-849552b7bfca.png">

As you can see all dependencies declared in `apps/esteem/Cargo.toml` are added as implicit dependencies. By definition, _only_ in-workspace projects qualify as implicitDependencies.So in the above example only `esteem_core` should be display in the graph.

I could not find any specific documentation for this, but you can test it easily by adding a random name to your `project.json`. 

As an example:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/60938164/182009743-f29e4498-7e08-4752-9621-1b0e97ca6bab.png">

And here is the output of `build`
<img width="910" alt="image" src="https://user-images.githubusercontent.com/60938164/182009755-97ddb6f5-d378-4cb6-8e22-b9666d897dc0.png">

The fix is pretty easy, and I am willing to make a PR for the same.

**Comment by IgnisDa** [comment]
I will make a PR for this once #21 is merged to prevent merge conflicts.

**Comment by IgnisDa** [comment]
@IgnisDa I wrote this plugin which solves the above problem. You can install it from NPM https://www.npmjs.com/package/@ignisda/nx-rust.

**Comment by dannymcgee** [comment]
This is fixed now — I was trying to emulate what Nx does with its own tracking of `npm` dependencies for JavaScript projects, but the way I was going about it was kind of a hack and probably not actually very useful.

External dependency tracking will be fixed properly once this plugin upgrades to Nx v19.x, but that won't happen until I can validate that the new Nx version doesn't cause any issues with my main project that's consuming this plugin.
