### ISSUE TITLE
project future and wasm support

### ISSUE THREAD

**Issue by noctifer20** [nxrs/cargo#27]
Hey guys, just recently discovered this plugin, wonderful idea!

I want to add `wasm` support with `wasm-pack` (here is pr #26), and for that I would like to know if you are going to continue to support the project?
If not, I'll publish my own module on `npm` with a link to this project as inspiration.

Cheers!

**Comment by ALMaclaine** [comment]
@noctifer20 please post to this issue and tag me if you end up publishing your own

**Comment by noctifer20** [comment]
@ALMaclaine here is initial working version tested with `nx`'s `TS` setup https://www.npmjs.com/package/@noctifer20/nx-cargo
I'll close this issue, for future issues please write in https://github.com/noctifer20/nx-cargo
