### ISSUE TITLE
[Bug Report] target handling in 0.4.0 introduces error with --configuration

### ISSUE THREAD

**Issue by leggomuhgreggo** [nxrs/cargo#31]
### Overview 

After the [0.4.0 update](https://github.com/nxrs/cargo/compare/v0.3.4...v0.4.0), cargo failed with this error message:
```console
> nx run foo-svc:test:ci 
> cargo test -p foo-svc --options "[object Object]"
error: unexpected argument '--options' found

  tip: a similar argument exists: '--timings'

Usage: cargo test --package [<SPEC>] --timings[=<FMTS>] [TESTNAME] [-- [args]...]

For more information, try '--help'.
```

### Context

In CI we run: 
```console
nx affected --target=test --configuration=ci
```

The extra configuration [[nx docs](https://nx.dev/core-features/plugin-features/use-task-executors#use-executor-configurations)] argument is required for one or two of our projects -- for other projects it's just ignored.

### Workaround

Easy enough to temporarily split out cargo tasks into it's own command w/o a configuration argument

Thanks!

**Comment by nutstick** [comment]
Hey @leggomuhgreggo what's the value of `configurations` in your `project.json`? I realized the new change in 0.4.0 will forward all options into the cargo arguments. If there's `options` in the configuration, might need to unfold/remove it as it's not an expected argument by cargo.

e.g.

This doesn't work, it parses into `--options "[object Object]"`
```
"configurations": {
  "ci": {
    "options": {
      "release": true
    }
  }
}
```

But this worked
```
"configurations": {
  "ci": {
    "release": true
  }
}
```
