### ISSUE TITLE
Cannot build app

### ISSUE THREAD

**Issue by Suyashtnt** [nxrs/cargo#5]
I am unable to build a cargo app using this. 

error:
```
glowsquid/apps/oxidize on  dev [!] is 📦 v0.1.0 via .NET v6.0.100 via 🦀 v1.57.0 took 3s
❯ yarn nx build oxidize    
yarn run v1.22.15
$ D:\projects\glowsquid\node_modules\.bin\nx build oxidize
error: could not find `Cargo.toml` in `D:\projects\glowsquid` or any parent directory
Failed to process the project graph with "@nxrs/cargo". This will error in the future!
Run with NX_VERBOSE_LOGGING=true to see the error.

> nx run oxidize:build 
> cargo build --bin oxidize
error: could not find `Cargo.toml` in `D:\projects\glowsquid` or any parent directory

———————————————————————————————————————————————

>  NX   ERROR  Running target "oxidize:build" failed

  Failed tasks:

  - oxidize:build

  Hint: run the command with --verbose for more details.


>  NX   CLOUD  See run details at https://nx.app/runs/sEGeeqGliP8

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems that when running the path that cargo runs in isnt correct

**Comment by dannymcgee** [comment]
Hey @Suyashtnt, would you be able to link me to the repo where you're seeing this issue? Or if it's not open source, if you could describe your project layout/directory structure and let me know what version of Nx you're using, I can start trying to narrow it down.

**Comment by dannymcgee** [comment]
Actually — did you generate the `oxidize` app with `nx generate @nxrs/cargo:app oxidize`, or did you manually create it? The plugin creates a [Cargo workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) at the root of your Nx workspace the first time you generate an app or library, and the executors assume the Cargo workspace already exists when they're doing their thing, so that might explain the problem. If that's the case, it should be a quick fix. (In the meantime, I'll go ahead and update the executors so they respond a little more gracefully when that happens.)

**Comment by Suyashtnt** [comment]
> Hey @Suyashtnt, would you be able to link me to the repo where you're seeing this issue? Or if it's not open source, if you could describe your project layout/directory structure and let me know what version of Nx you're using, I can start trying to narrow it down.

The repo is glowsquid-launcher/glowsquid

**Comment by Suyashtnt** [comment]
> Actually — did you generate the `oxidize` app with `nx generate @nxrs/cargo:app oxidize`, or did you manually create it? The plugin creates a [Cargo workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) at the root of your Nx workspace the first time you generate an app or library, and the executors assume the Cargo workspace already exists when they're doing their thing, so that might explain the problem.
> 
> If that's the case, it should be a quick fix: Try running `yarn nx generate @nxrs/cargo:init`, and then adding `"apps/oxidize"` to the `workspace.members` array in the root-level Cargo.toml that gets generated.
> 
> In the meantime, I'll go ahead and update the executors so they respond a little more gracefully when that happens. I'm also now seeing that the app/lib generators fail if you don't have any existing Nx projects in the workspace, which is kind of a bummer — I'll look into that as well.

I'll try that

**Comment by dannymcgee** [comment]
Hey @Suyashtnt, I actually just noticed you've got a Tauri config file in your `oxidize` project. I've done a little bit of playing around with Tauri, and I think it actually requires a fairly unique setup compared to what this plugin can do. I have [another Nx project](https://github.com/electric-io/electric) where I set up an ad-hoc builder for a Tauri app using `@nrwl/workspace:run-commands` — you may have better luck with a something like that. The Tauri project is under `demos/tauri-app` if you want to take a look.

**Comment by Suyashtnt** [comment]
> Hey @Suyashtnt, I actually just noticed you've got a Tauri config file in your `oxidize` project. I've done a little bit of playing around with Tauri, and I think it actually requires a fairly unique setup compared to what this plugin can do. I have [another Nx project](https://github.com/electric-io/electric) where I set up an ad-hoc builder for a Tauri app using `@nrwl/workspace:run-commands` — you may have better luck with a something like that. The Tauri project is under `demos/tauri-app` if you want to take a look.

the setup is going to be much easier in the future but ill try using something similar to your demo, thanks
