### ISSUE TITLE
Not an issue but big thanks.

### ISSUE THREAD

**Issue by kunjee17** [nxrs/cargo#6]
Hi, I was trying to do similar when I found .Net and Go support. But couldn't do it due to time constraint. But you created. And I was more than happy to delete my repo. 

thanks for whoever is working on this Repo. I will be soon love to take it for a spin. I have quite a big workspace for client project. 

Thanks again. And you can close the issue if you like. :)

**Comment by dannymcgee** [comment]
You're very welcome, happy it's helpful! :)
